image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
         script:
          - pipe: atlassian/rsync-deploy:0.3.2
            variables:
              USER: 'oleg'
              SERVER: 'clients.pdmdev.co'
              REMOTE_PATH: '/var/www/clients/sib.pdmdev.co/wp-content/themes/powertheme'
              LOCAL_PATH: './'
              EXTRA_ARGS: '--no-perms --no-owner --no-group'